# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4713f86162fce242ef989ec7969115c8cc53a037c3fcb68f884d54ec77063249c3e66e3fa5c43ac86aa60a9afa80ee5ced8260af663d2804eb45a80cd395b19d

test:
  secret_key_base: e019c24aa600e141083afb246e93a0ddd85b34ba67157aa5bf3c171b6faf3c1b2ee59fe0a2632a154001c53617ebb54145e31db9d76f181e102b4f450466583e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
